// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcnEYr_kahmPWG9U-ZgRSrG7kEWMDK2TA',
    appId: '1:16622816538:web:e89203dbbfecef898cb0a3',
    messagingSenderId: '16622816538',
    projectId: 'baato-mechanic',
    authDomain: 'baato-mechanic.firebaseapp.com',
    storageBucket: 'baato-mechanic.appspot.com',
    measurementId: 'G-HS4QXTNY3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_I9YRpcAzIwwi4cXOaXLZFTxt-fARIkQ',
    appId: '1:16622816538:android:65a3ef46b78078518cb0a3',
    messagingSenderId: '16622816538',
    projectId: 'baato-mechanic',
    storageBucket: 'baato-mechanic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01AODxRX4lkfbupnJGLOVrJCooDac--s',
    appId: '1:16622816538:ios:638b8975aceb36d18cb0a3',
    messagingSenderId: '16622816538',
    projectId: 'baato-mechanic',
    storageBucket: 'baato-mechanic.appspot.com',
    androidClientId:
        '16622816538-407o5q83ghu21hkemff2ipg517ldhuel.apps.googleusercontent.com',
    iosBundleId: 'com.example.mechanic.app',
  );
}
